name: mirror-psbook

on:
  workflow_dispatch:

jobs:
  generate:
    name: Mirror Picture-story Book on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions:
      contents: write
      # issues: write # 重写了 permissions，故而需要额外添加 contents 权限，不然 git clone 会失败
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout psbook_1
        uses: actions/checkout@v3
        with:
          repository: Vast-As-A-Sea/Journey-to-the-West-comic-series-part1
          ref: main
          path: psbook_1
      - name: Checkout psbook_2
        uses: actions/checkout@v3
        with:
          repository: Vast-As-A-Sea/Journey-to-the-West-comic-series-part2
          ref: main
          path: psbook_2
      - name: Checkout psbook_3
        uses: actions/checkout@v3
        with:
          repository: Vast-As-A-Sea/Journey-to-the-West-comic-series-part3
          ref: main
          path: psbook_3
      - name: Checkout psbook_4
        uses: actions/checkout@v3
        with:
          repository: Vast-As-A-Sea/Journey-to-the-West-comic-series-part4
          ref: main
          path: psbook_4
      - name: Checkout psbook_5
        uses: actions/checkout@v3
        with:
          repository: Vast-As-A-Sea/Journey-to-the-West-comic-series-part5
          ref: main
          path: psbook_5
      - name: Checkout psbook_6
        uses: actions/checkout@v3
        with:
          repository: Vast-As-A-Sea/Journey-to-the-West-comic-series-part6
          ref: main
          path: psbook_6
      - name: Merge Github Pages
        run: |
          mkdir -p merge
          rm -rf psbook_1/.git && rm psbook_1/.gitattributes && rm psbook_1/LICENSE && cp -r psbook_1/. merge/
          rm -rf psbook_2/.git && rm psbook_2/.gitattributes && rm psbook_2/LICENSE && cp -r psbook_2/. merge/
          rm -rf psbook_3/.git && rm psbook_3/.gitattributes && rm psbook_3/LICENSE && cp -r psbook_3/. merge/
          rm -rf psbook_4/.git && rm psbook_4/.gitattributes && rm psbook_4/LICENSE && cp -r psbook_4/. merge/
          rm -rf psbook_5/.git && rm psbook_5/.gitattributes && rm psbook_5/LICENSE && cp -r psbook_5/. merge/
          rm -rf psbook_6/.git && rm psbook_6/.gitattributes && rm psbook_6/LICENSE && cp -r psbook_6/. merge/
      - name: Deploy Merge
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: merge
          branch: main
